sudo: required
services:
  - docker

script: npm test
language: node_js
before_install:
  - docker pull nats:latest
  - docker run --name=nats -p 4222:4222 -d nats:latest
  - docker ps -a
git:
  depth: 3
node_js:
  - "6"
  - "7"
  - "8"
addons:
  code_climate:
    repo_token: 248135f96061f77d2e5f78526432fd096785d2914d8f5a73a04c061000939d5d
env:
  - NODE_ENV=test
