version: '2'
services:
  node-1:
    build: ../
    environment:
      DEBUG: '*'
      channel__host: 'node-1'
      seeds: 'node-1:3455,node-2:3456'
  node-2:
    build: ../
    environment:
      DEBUG: '*'
      seeds: 'node-1:3455,node-2:3456'
      channel__host: 'node-2'
      channel__port: 3456
  node-3:
    build: ../
    environment:
      DEBUG: '*'
      seeds: 'node-1:3455,node-2:3456'
      channel__host: 'node-3'
  node-4:
    build: ../
    environment:
      DEBUG: '*'
      seeds: 'node-1:3455,node-2:3456'
      channel__host: 'node-4'
  node-5:
    build: ../
    environment:
      DEBUG: '*'
      seeds: 'node-1:3455,node-2:3456'
      channel__host: 'node-5'

  nginx:
    image: 'nginx:latest'
    volumes:
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    depends_on:
      - node-1
      - node-2
      - node-3
      - node-4
      - node-5

