version: '2'
services:
  node-1:
    build: ../
    environment:
      DEBUG: '*'
      channel__host: 'node-1'
      nats__hosts: 'nats-a:4222,nats-b:4222,nats-c:4222'
      seeds: 'node-1:3455,node-2:3456'
      storage__backend: 'leveldown'
      storage__path: /var/data/skyring
    networks:
      - skyring
    depends_on:
      - nats-a
      - nats-b
      - nats-c

  node-2:
    build: ../
    environment:
      DEBUG: '*'
      seeds: 'node-1:3455,node-2:3456'
      nats__hosts: 'nats-a:4222,nats-b:4222,nats-c:4222'
      channel__host: 'node-2'
      channel__port: 3456
      storage__backend: 'memdown'
      storage__path: /var/data/skyring
    networks:
      - skyring
    depends_on:
      - nats-a
      - nats-b
      - nats-c

  node-3:
    build: ../
    environment:
      DEBUG: '*'
      seeds: 'node-1:3455,node-2:3456'
      nats__hosts: 'nats-a:4222,nats-b:4222,nats-c:4222'
      channel__host: 'node-3'
      storage__backend: 'leveldown'
      storage__path: /var/data/skyring
    networks:
      - skyring
    depends_on:
      - nats-a
      - nats-b
      - nats-c
      - node-1
      - node-2

  node-4:
    build: ../
    environment:
      DEBUG: '*'
      seeds: 'node-1:3455,node-2:3456'
      nats__hosts: 'nats-a:4222,nats-b:4222,nats-c:4222'
      channel__host: 'node-4'
      storage__backend: 'leveldown'
      storage__path: /var/data/skyring
    networks:
      - skyring
    depends_on:
      - nats-a
      - nats-b
      - nats-c
      - node-1
      - node-2

  node-5:
    build: ../
    environment:
      DEBUG: '*'
      seeds: 'node-1:3455,node-2:3456'
      nats__hosts: 'nats-a:4222,nats-b:4222,nats-c:4222'
      channel__host: 'node-5'
      storage__backend: 'leveldown'
      storage__path: /var/data/skyring
    networks:
      - skyring
    depends_on:
      - nats-a
      - nats-b
      - nats-c

  nats-a:
    image: nats:latest
    volumes:
      - ./etc/nats:/tmp
    command: >
      -c /tmp/a.conf -D
    networks:
      - skyring
  nats-b:
    image: nats:latest
    volumes:
      - ./etc/nats:/tmp
    command: >
      -c /tmp/b.conf -D
    depends_on:
      - nats-a
    networks:
      - skyring
  nats-c:
    image: nats:latest
    volumes:
      - ./etc/nats:/tmp
    depends_on:
      - nats-a
    command: >
      -c /tmp/c.conf -D
    networks:
      - skyring

  nginx:
    image: 'nginx:latest'
    volumes:
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    networks:
      - skyring
    depends_on:
      - node-1
      - node-2
      - node-3
      - node-4
      - node-5

networks:
  skyring:
    driver: bridge
