version: '2'
services:
  node-1:
    build: ../
    hostname: node-1
    environment:
      DEBUG: '*'
      channel__host: 'node-1'
      nats__hosts: 'nats-a:4222,nats-b:4222,nats-c:4222'
      seeds: 'node-1:3455,node-2:3456'
      storage__backend: 'leveldown'
      storage__path: /var/data/skyring-1
      statsd__host: telegraf
      statsd__port: 8125
      statsd__cacheDns: true
      statsd__telegraf: true
    networks:
      - skyring
    depends_on:
      - nats-a
      - nats-b
      - nats-c

  node-2:
    build: ../
    hostname: node-2
    environment:
      DEBUG: '*'
      seeds: 'node-1:3455,node-2:3456'
      nats__hosts: 'nats-a:4222,nats-b:4222,nats-c:4222'
      channel__host: 'node-2'
      channel__port: 3456
      storage__backend: 'memdown'
      storage__path: /var/data/skyring-2
    networks:
      - skyring
    depends_on:
      - nats-a
      - nats-b
      - nats-c

  node-3:
    build: ../
    hostname: node-3
    environment:
      DEBUG: '*'
      seeds: 'node-1:3455,node-2:3456'
      nats__hosts: 'nats-a:4222,nats-b:4222,nats-c:4222'
      channel__host: 'node-3'
      storage__backend: 'leveldown'
      storage__path: /var/data/skyrin-3
    networks:
      - skyring
    depends_on:
      - nats-a
      - nats-b
      - nats-c
      - node-1
      - node-2

  node-4:
    build: ../
    hostname: node-4
    environment:
      DEBUG: '*'
      seeds: 'node-1:3455,node-2:3456'
      nats__hosts: 'nats-a:4222,nats-b:4222,nats-c:4222'
      channel__host: 'node-4'
      storage__backend: 'leveldown'
      storage__path: /var/data/skyring-4
    networks:
      - skyring
    depends_on:
      - nats-a
      - nats-b
      - nats-c
      - node-1
      - node-2

  node-5:
    build: ../
    hostname: node-5
    environment:
      DEBUG: '*'
      seeds: 'node-1:3455,node-2:3456'
      nats__hosts: 'nats-a:4222,nats-b:4222,nats-c:4222'
      channel__host: 'node-5'
      storage__backend: 'leveldown'
      storage__path: /var/data/skyring-5
    networks:
      - skyring
    depends_on:
      - nats-a
      - nats-b
      - nats-c
      - node-1
      - node-2
      - node-3
      - node-4

  nats-a:
    image: nats:latest
    volumes:
      - ./etc/nats:/tmp
    command: >
      -c /tmp/a.conf -D
    networks:
      - skyring
  nats-b:
    image: nats:latest
    volumes:
      - ./etc/nats:/tmp
    command: >
      -c /tmp/b.conf -D
    depends_on:
      - nats-a
    networks:
      - skyring
  nats-c:
    image: nats:latest
    volumes:
      - ./etc/nats:/tmp
    depends_on:
      - nats-a
    command: >
      -c /tmp/c.conf -D
    networks:
      - skyring

  influxdb:
    image: influxdb:alpine
    environment:
      INFLUXDB_GRAPHITE_ENABLED: 1
      INFLUXDB_ADMIN_ENABLED: 1
    ports:
      - 8060:8060
      - 8083:8083
      - 2003:2003
    networks:
      - skyring

  chronograf:
    image: chronograf:alpine
    environment:
      INFLUXDB_URL: http://influxdb:8086
    networks:
      - skyring
    ports:
      - 8888:8888
    command: >
      chronograf --influxdb-url=http://influxdb:8086

  telegraf:
    image: telegraf:1.6-alpine
    volumes:
      - ./etc/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    networks:
      - skyring
    ports:
      - 8125:8125/udp
      - 8092:8092
      - 8094:8094

  nginx:
    image: 'nginx:latest'
    volumes:
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    networks:
      - skyring
    depends_on:
      - node-1
      - node-2
      - node-3
      - node-4
      - node-5

networks:
  skyring:
    driver: bridge
