version: '2'
services:
  nats-a:
    image: nats:latest
    volumes:
      - ./etc/nats:/tmp
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
    command: >
      -c /tmp/a.conf -D
    networks:
      - nats
  nats-b:
    image: nats:latest
    ports:
      - "4223:4222"
    volumes:
      - ./etc/nats:/tmp
    command: >
      -c /tmp/b.conf -D
    depends_on:
      - nats-a
    networks:
      - nats
  nats-c:
    image: nats:latest
    volumes:
      - ./etc/nats:/tmp
    depends_on:
      - nats-a
    command: >
      -c /tmp/c.conf -D
    networks:
      - nats

networks:
  nats:
    driver: bridge
