version: '2'
services:
  nats-a:
    image: nats:latest
    volumes:
      - ./etc/nats:/tmp
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
    command: >
      -c /tmp/a.conf -D
    networks:
      - nats
  nats-b:
    image: nats:latest
    ports:
      - "4223:4222"
    volumes:
      - ./etc/nats:/tmp
    command: >
      -c /tmp/b.conf -D
    depends_on:
      - nats-a
    networks:
      - nats
  nats-c:
    image: nats:latest
    volumes:
      - ./etc/nats:/tmp
    depends_on:
      - nats-a
    command: >
      -c /tmp/c.conf -D
    networks:
      - nats

  influxdb:
    image: influxdb:alpine
    environment:
      INFLUXDB_GRAPHITE_ENABLED: 1
      INFLUXDB_ADMIN_ENABLED: 1
    ports:
      - 8060:8060
      - 8083:8083
      - 2003:2003
    networks:
      - nats

  chronograf:
    image: chronograf:alpine
    environment:
      INFLUXDB_URL: http://influxdb:8086
    networks:
      - nats
    ports:
      - 8888:8888
    command: >
      chronograf --influxdb-url=http://influxdb:8086

  telegraf:
    image: telegraf:1.6-alpine
    volumes:
      - ./etc/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    networks:
      - nats
    ports:
      - 8125:8125/udp
      - 8092:8092
      - 8094:8094

networks:
  nats:
    driver: bridge
